# Ejercicio 1
    
    1.- Crear un vector "x" con 10 ceros y mostrarlo.
    2.- Modificar el quinto elemento del vector x para que su valor sea 3.
    3.- Crear un vector "y" con valores del 1 al 20, de 1 en 1. Utiliza la función arange.
    4.- Crear un vector "z" con valores del 1 al 20, de 2 en 2.
    5.- Crear una matrz w de 3 x 2, son valores iniciales en 0.
    6.- Modificar el elemento de la posición 2,2 de la matriz 2 para que su valor sea 5.
    7.- Crear un vector de 5 elementos, con valores aleatorios enteros entre 1 y 10.
    8.- Crear el arreglo x1 de la lista [1,2,3]
    9.- Sumar 10 a cada elemento del vector.

In [1]:
#    Importar Librerías
import numpy as np

In [2]:
#    1.- Crear un vector "x" con 10 ceros y mostrarlo.
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#   2.- Modificar el quinto elemento del vector x para que su valor sea 3.
x[4] = 3
x

array([0., 0., 0., 0., 3., 0., 0., 0., 0., 0.])

In [4]:
#   3.- Crear un vector "y" con valores del 1 al 20, de 1 en 1. Utiliza la función arange.
y = np.arange(1,21)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
#   4.- Crear un vector "z" con valores del 1 al 20, de 2 en 2.
z = np.arange(1,21,2)
z

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
#   5.- Crear una matrz w de 3 x 2, son valores iniciales en 0.
w = np.zeros((3,2))
w

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
#   6.- Modificar el elemento de la posición 2,2 de la matriz 2 para que su valor sea 5.
w[1,1] = 5
w

array([[0., 0.],
       [0., 5.],
       [0., 0.]])

In [8]:
#   7.- Crear un vector de 5 elementos, con valores aleatorios enteros entre 1 y 10.
arr = np.random.randint(1,11, size=5)
arr

array([4, 6, 3, 3, 1])

In [9]:
#   8.- Crear el arreglo x1 de la lista [1,2,3]
x_1 = np.array([1,2,3])
x_2 = [1,2,3]
x_1

array([1, 2, 3])

In [10]:
x_2

[1, 2, 3]

In [11]:
#   9.- Sumar 10 a cada elemento del vector.
x_1 = x_1 + 10
x_1

array([11, 12, 13])